# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/M/Desktop/Basys3_Master.xdc

# Block Designs: bd/MainDesign/MainDesign.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign || ORIG_REF_NAME==MainDesign} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_dff_0_0/MainDesign_xup_dff_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_dff_0_0 || ORIG_REF_NAME==MainDesign_xup_dff_0_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_dff_0_1/MainDesign_xup_dff_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_dff_0_1 || ORIG_REF_NAME==MainDesign_xup_dff_0_1} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_dff_0_2/MainDesign_xup_dff_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_dff_0_2 || ORIG_REF_NAME==MainDesign_xup_dff_0_2} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_dff_0_3/MainDesign_xup_dff_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_dff_0_3 || ORIG_REF_NAME==MainDesign_xup_dff_0_3} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_dff_0_4/MainDesign_xup_dff_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_dff_0_4 || ORIG_REF_NAME==MainDesign_xup_dff_0_4} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_or5_0_0/MainDesign_xup_or5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_or5_0_0 || ORIG_REF_NAME==MainDesign_xup_or5_0_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_or2_0_0/MainDesign_xup_or2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_or2_0_0 || ORIG_REF_NAME==MainDesign_xup_or2_0_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_inv_0_0/MainDesign_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_inv_0_0 || ORIG_REF_NAME==MainDesign_xup_inv_0_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_inv_0_1/MainDesign_xup_inv_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_inv_0_1 || ORIG_REF_NAME==MainDesign_xup_inv_0_1} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_inv_0_2/MainDesign_xup_inv_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_inv_0_2 || ORIG_REF_NAME==MainDesign_xup_inv_0_2} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_and3_0_0/MainDesign_xup_and3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_and3_0_0 || ORIG_REF_NAME==MainDesign_xup_and3_0_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_and2_0_0/MainDesign_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_and2_0_0 || ORIG_REF_NAME==MainDesign_xup_and2_0_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_and2_0_1/MainDesign_xup_and2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_and2_0_1 || ORIG_REF_NAME==MainDesign_xup_and2_0_1} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_or2_0_1/MainDesign_xup_or2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_or2_0_1 || ORIG_REF_NAME==MainDesign_xup_or2_0_1} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_inv_2_0/MainDesign_xup_inv_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_inv_2_0 || ORIG_REF_NAME==MainDesign_xup_inv_2_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_and2_0_2/MainDesign_xup_and2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_and2_0_2 || ORIG_REF_NAME==MainDesign_xup_and2_0_2} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_and2_0_3/MainDesign_xup_and2_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_and2_0_3 || ORIG_REF_NAME==MainDesign_xup_and2_0_3} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_inv_3_0/MainDesign_xup_inv_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_inv_3_0 || ORIG_REF_NAME==MainDesign_xup_inv_3_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_and2_2_0/MainDesign_xup_and2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_and2_2_0 || ORIG_REF_NAME==MainDesign_xup_and2_2_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_or2_1_0/MainDesign_xup_or2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_or2_1_0 || ORIG_REF_NAME==MainDesign_xup_or2_1_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_and2_3_0/MainDesign_xup_and2_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_and2_3_0 || ORIG_REF_NAME==MainDesign_xup_and2_3_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_and3_1_0/MainDesign_xup_and3_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_and3_1_0 || ORIG_REF_NAME==MainDesign_xup_and3_1_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_and3_1_1/MainDesign_xup_and3_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_and3_1_1 || ORIG_REF_NAME==MainDesign_xup_and3_1_1} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_or2_2_0/MainDesign_xup_or2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_or2_2_0 || ORIG_REF_NAME==MainDesign_xup_or2_2_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_and2_2_1/MainDesign_xup_and2_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_and2_2_1 || ORIG_REF_NAME==MainDesign_xup_and2_2_1} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_and2_1_0/MainDesign_xup_and2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_and2_1_0 || ORIG_REF_NAME==MainDesign_xup_and2_1_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_or2_3_0/MainDesign_xup_or2_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_or2_3_0 || ORIG_REF_NAME==MainDesign_xup_or2_3_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_inv_4_0/MainDesign_xup_inv_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_inv_4_0 || ORIG_REF_NAME==MainDesign_xup_inv_4_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_inv_4_1/MainDesign_xup_inv_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_inv_4_1 || ORIG_REF_NAME==MainDesign_xup_inv_4_1} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_and5_0_0/MainDesign_xup_and5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_and5_0_0 || ORIG_REF_NAME==MainDesign_xup_and5_0_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_and2_8_0/MainDesign_xup_and2_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_and2_8_0 || ORIG_REF_NAME==MainDesign_xup_and2_8_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_or2_3_1/MainDesign_xup_or2_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_or2_3_1 || ORIG_REF_NAME==MainDesign_xup_or2_3_1} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_or2_6_0/MainDesign_xup_or2_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_or2_6_0 || ORIG_REF_NAME==MainDesign_xup_or2_6_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_and2_8_1/MainDesign_xup_and2_8_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_and2_8_1 || ORIG_REF_NAME==MainDesign_xup_and2_8_1} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_and2_10_0/MainDesign_xup_and2_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_and2_10_0 || ORIG_REF_NAME==MainDesign_xup_and2_10_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_and2_11_0/MainDesign_xup_and2_11_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_and2_11_0 || ORIG_REF_NAME==MainDesign_xup_and2_11_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_or2_5_0/MainDesign_xup_or2_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_or2_5_0 || ORIG_REF_NAME==MainDesign_xup_or2_5_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_clk_divider_0_0/MainDesign_xup_clk_divider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_clk_divider_0_0 || ORIG_REF_NAME==MainDesign_xup_clk_divider_0_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_dff_5_0/MainDesign_xup_dff_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_dff_5_0 || ORIG_REF_NAME==MainDesign_xup_dff_5_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_dff_5_1/MainDesign_xup_dff_5_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_dff_5_1 || ORIG_REF_NAME==MainDesign_xup_dff_5_1} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_dff_5_2/MainDesign_xup_dff_5_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_dff_5_2 || ORIG_REF_NAME==MainDesign_xup_dff_5_2} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_and3_3_0/MainDesign_xup_and3_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_and3_3_0 || ORIG_REF_NAME==MainDesign_xup_and3_3_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_clk_divider_1_0/MainDesign_xup_clk_divider_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_clk_divider_1_0 || ORIG_REF_NAME==MainDesign_xup_clk_divider_1_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_dff_5_3/MainDesign_xup_dff_5_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_dff_5_3 || ORIG_REF_NAME==MainDesign_xup_dff_5_3} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_dff_5_4/MainDesign_xup_dff_5_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_dff_5_4 || ORIG_REF_NAME==MainDesign_xup_dff_5_4} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_dff_5_5/MainDesign_xup_dff_5_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_dff_5_5 || ORIG_REF_NAME==MainDesign_xup_dff_5_5} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_and3_3_1/MainDesign_xup_and3_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_and3_3_1 || ORIG_REF_NAME==MainDesign_xup_and3_3_1} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_dff_10_0/MainDesign_xup_dff_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_dff_10_0 || ORIG_REF_NAME==MainDesign_xup_dff_10_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_dff_10_1/MainDesign_xup_dff_10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_dff_10_1 || ORIG_REF_NAME==MainDesign_xup_dff_10_1} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_dff_10_2/MainDesign_xup_dff_10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_dff_10_2 || ORIG_REF_NAME==MainDesign_xup_dff_10_2} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_and3_4_0/MainDesign_xup_and3_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_and3_4_0 || ORIG_REF_NAME==MainDesign_xup_and3_4_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_2_to_1_mux_0_0/MainDesign_xup_2_to_1_mux_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_2_to_1_mux_0_0 || ORIG_REF_NAME==MainDesign_xup_2_to_1_mux_0_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xup_2_to_1_mux_0_1/MainDesign_xup_2_to_1_mux_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xup_2_to_1_mux_0_1 || ORIG_REF_NAME==MainDesign_xup_2_to_1_mux_0_1} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xlconstant_0_0/MainDesign_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xlconstant_0_0 || ORIG_REF_NAME==MainDesign_xlconstant_0_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xlconstant_0_1/MainDesign_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xlconstant_0_1 || ORIG_REF_NAME==MainDesign_xlconstant_0_1} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_seg7display_0_1/MainDesign_seg7display_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_seg7display_0_1 || ORIG_REF_NAME==MainDesign_seg7display_0_1} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xlconcat_0_0/MainDesign_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xlconcat_0_0 || ORIG_REF_NAME==MainDesign_xlconcat_0_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xlconstant_2_0/MainDesign_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xlconstant_2_0 || ORIG_REF_NAME==MainDesign_xlconstant_2_0} -quiet] -quiet

# IP: bd/MainDesign/ip/MainDesign_xlconstant_2_1/MainDesign_xlconstant_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MainDesign_xlconstant_2_1 || ORIG_REF_NAME==MainDesign_xlconstant_2_1} -quiet] -quiet

# XDC: bd/MainDesign/MainDesign_ooc.xdc
